  - name: take cert from letsencrypt
    shell:
      cmd: /usr/bin/letsencrypt certonly --webroot -d {{ tls_vhostnames }} -d www.{{ tls_vhostnames }} -w /opt/www/{{ tls_dir_names }} -m {{ letsencrypt_renew_email }} --agree-tos 
    tags:
      - letsencrypt_cert
    notify: 
      - reload nginx        

  - name: Add letsencrypt cronjob for cert renewal
    cron:
      name: letsencrypt_renewal
      special_time: weekly
      job: /usr/bin/letsencrypt --renew-by-default certonly -n --webroot -w /opt/www/{{ tls_dir_names }}  -m {{ letsencrypt_renew_email }} --agree-tos -d {{ tls_vhostnames }} -d www.{{ tls_vhostnames }} && /etc/init.d/nginx reload
    tags:
      - cron_cert
    notify: 
      - reload nginx               

  - name: copy the new 443 nginx vhotsts config file
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}" 
    with_items:
      - "{{ virtualconf }}"
    tags:
      - new_host 
    notify: 
      - reload nginx     